### ISSUE TITLE
Unable to give correct URI for postgresql database in yml file for GitHub Actions

### ISSUE THREAD

**Issue by JuzerShakir** [JuzerShakir/github-action-test#1]
I am implementing **[GitHub actions][1]** for the first time and I am unable to pass the test successfully for my Ruby On Rails project. The reason is that I am unable to provide the correct URI for the PostgreSQL server.

When I push the code to the GitHub via `git push`, a test begins successfully as expected, but it fails to pass with this error:
```
URI::InvalidURIError: bad URI(is not URI?): postgres:***:***@localhost:5432/github_actions_test
```

I have a username and password set in my GitHub secrets.

I have provided a constant to hold the value of the URI in my yml file as:
```yml
DATABASE_URL = "postgres://username:password@localhost:5432/github_actions_test"
```

Now replacing `username` & `password` with mine, since my DB credentials are already available in secrets:
```yml
DATABASE_URL = "postgres://${{secrets.DATABASE_USERNAME}}:${{secrets.DATABASE_PASSWORD}}@localhost:5432/github_actions_test"
```
this doesn't work and it gave same error as mentioned above. Then I tried as this:

```yml
DATABASE_URL = "postgres://<%=secrets.DATABASE_USERNAME%>:<%=secrets.DATABASE_PASSWORD%>@localhost:5432/github_actions_test"
```
this also resulted in the same error.

Then to test whether the DATABASE_URL really works, I explicitly gave DB credentials in the URI. I know it's not recommended but I had to, to test things out and that also resulted in the same error.

I also tried to save the DB URL in my secrets and then call in my yml file as I did with my DB credentials but that didn't work too.

So my question is how do I make the PostgreSQL URI work in GitHub actions? Is there some other way to set it up or may be my string interpolation is wrong? Or may be I am doing something else wrong?

Here's the code inside of my yml file:
```yml
# This workflow uses actions that are not certified by GitHub.  They are
# provided by a third-party and are governed by separate terms of service,
# privacy policy, and support documentation.
#
# This workflow will install a prebuilt Ruby version, install dependencies, and
# run tests and linters.
name: "Ruby on Rails CI"
on:
  push:
    branches: ["rspec"]
  pull_request:
    branches: ["rspec"]
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: github_actions_test
          POSTGRES_USER: ${{ secrets.DATABASE_USERNAME }}
          POSTGRES_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://username:password@localhost:5432/github_actions_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # Add or replace dependency steps here
      - name: Install Ruby and gems
        uses: ruby/setup-ruby@0a29871fe2b0200a17a4497bae54fe5df0d973aa # v1.115.3
        with:
          bundler-cache: true
          ruby-version: 3.1.2
      # Add or replace database setup steps here
      - name: Setup Ruby
        run: sudo apt-get -yqq install libpq-dev

      - name: Setup bundler and gems
        run: |
          gem install bundler
          bundle install --jobs 4 --retry 3

      - name: Set up database schema
        run: bin/rails db:prepare

      # Add or replace test runners here
      - name: Run tests
        run: bundle/exec rspec

  # lint:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3
  #     - name: Install Ruby and gems
  #       uses: ruby/setup-ruby@0a29871fe2b0200a17a4497bae54fe5df0d973aa # v1.115.3
  #       with:
  #         bundler-cache: true
  #     # Add or replace any other lints here
  #     - name: Security audit dependencies
  #       run: bin/bundler-audit --update
  #     - name: Security audit application code
  #       run: bin/brakeman -q -w2
  #     - name: Lint Ruby files
  #       run: bin/rubocop --parallel
```

  [1]: https://github.com/features/actions
